version: 0.2 

phases:
  pre_build:
    commands:
      - echo PreBuild Started ...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 274201610284.dkr.ecr.ap-south-1.amazonaws.com
#      - aws ecr-public  get-login-password  --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws/p2e3u7x0
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t 839866-pension-process-service .
#      - docker build -t pension-process-service .
      - docker tag 839866-pension-process-service:latest 274201610284.dkr.ecr.ap-south-1.amazonaws.com/839866-pension-process-service:latest
#      - docker tag pension-process-service public.ecr.aws/p2e3u7x0/841331-pension-process-service:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 274201610284.dkr.ecr.ap-south-1.amazonaws.com/839866-pension-process-service:latest
#      - docker push public.ecr.aws/p2e3u7x0/841331-pension-process-service:latest
      - echo Writing definition files
      - printf '[{"name":"839866-pension-process-service","imageUri":"%s"}]' 274201610284.dkr.ecr.ap-south-1.amazonaws.com/839866-pension-process-service:latest > imageDefinition.json

artifacts:
  files: 
    - imageDefinition.json
